version: '3.7'
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        stdin_open: true         # a trick to fix a unknown bug of creat-react-app
        links:
            - backend
        ports:
            - "3000:3000"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        ports:
            - "5000:5000"
        env_file:
          - ./backend/application/.env
        links:
            - mysql
        restart: "always"


    mysql:
        image: mysql:latest
        container_name: mysql
#        environment:
#            - MYSQL_USER=root
#            - MYSQL_ROOT_PASSWORD=your_database_password
        env_file:
          - ./backend/application/.env
        volumes:
            - ./backend/data/mysql:/data
        ports:
            - "3306:3306"
        restart: always


    nginx:
        image: nginx:latest
        container_name: nginx
        ports: 
            - "8080:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf


    redis:
        image: redis:latest
        container_name: redis
        volumes: 
            - ./backend/data/redis:/data
        ports:
            - "6379:6379"
        restart: always
