version: '3.7'
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: prod
        container_name: frontend
        stdin_open: true         # a trick to fix a unknown bug of creat-react-app
        ports:
            - "3000:3000"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
            target: prod
        container_name: backend
        ports:
            - "5000:5000"
        env_file:
          - ./backend/application/.env
        depends_on:
            - mysql
            - redis
        restart: "always"

    mysql:
        image: mysql:8.0.23
        container_name: mysql
        env_file:
          - ./backend/application/.env
        volumes:
            - ./mount/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: always

    nginx:
        image: nginx:1.19.9
        container_name: nginx
        ports: 
            - "80:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
          - frontend
          - backend
        restart: always

    redis:
        image: redis:6.2.1
        container_name: redis
        volumes: 
            - ./mount/redis:/data
        ports:
            - "6379:6379"
        restart: always
