version: '3.7'
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        stdin_open: true
        ports:
            - "3000:3000"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        ports:
            - "5000:5000"
        env_file:
          - ./backend/.env
        links:
            - mysql
        restart: "always"


    mysql:
        image: mysql:latest
        container_name: mysql
        environment: 
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=your_database_password
        volumes: 
            - ./data/mysql:/data
        restart: always


    nginx:
        image: nginx:latest
        container_name: nginx
        ports: 
            - "8080:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf


    redis:
        image: redis:latest
        container_name: redis
        volumes: 
            - ./data/redis:/data
        restart: always
    